### ISSUE TITLE
SPIKE: As a developer, I need to learn how to have an Angular application inside a Spring Boot application

### ISSUE THREAD

**Issue by ghost** [Access-Point-Program/cohort-3-reports#13]
We need to research to have an Angular application hosted by the Spring Boot API.

### Hint
- Check out the spring guides on the website

### Acceptance Criteria
- [x] Documented artifacts on how to put and host an Angular application within a spring application
- [x] Documenting our findings in the Google Site

**Comment by Dpppatel** [comment]
resources i found and trying to implement so i can make it easier for the team : 
[](https://github.com/dsyer/spring-boot-angular/tree/main )
[](https://angular.io/guide/ngmodules )
[](https://spring.io/guides/tutorials/react-and-spring-data-rest/)

**Comment by Dpppatel** [comment]
https://stackoverflow.com/questions/40717449/how-to-change-angular-port-from-4200-to-any-other

**Comment by Dpppatel** [comment]
https://projectlombok.org/features/

https://spring.io/projects/
