### ISSUE TITLE
SPIKE: Research how to use bootstrap with Angular

### ISSUE THREAD

**Issue by chris-marfia** [Access-Point-Program/cohort-3-reports#39]
We should utilize the Angular component library. We will need to learn how to use it and which components we might be using. 

---

## Resources
- [Angular Compontents](https://ng-bootstrap.github.io/#/components/accordion/overview)
- [Bootstrap Docs](https://getbootstrap.com/docs/5.3/getting-started/introduction/)

## Acceptance Criteria
- [x] Have team agreement if we are going to use the component library or not

**Comment by Dpppatel** [comment]
Decided: [Agular Components](https://ng-bootstrap.github.io/#/components/table/examples)

**Comment by Dpppatel** [comment]
Using components : Table, Pagination, Dropdown.
