### ISSUE TITLE
As a user I want to view details

### ISSUE THREAD

**Issue by JoshHaase0** [Access-Point-Program/cohort-3-reports#4]
**GIVEN** Data points are loaded
**WHEN** The user clicks "view details" button on a data point
**THEN** An analysis display is shown for the data point

### Acceptance Criteria
- [ ] Data points are displayed on the reports page
- [ ] A button with the label "view details" is in a tab for each data point
- [ ] When the "view details" button is clicked an event handler fires that displays an analysis page
- [ ] This feature is unit tested

**Comment by Dpppatel** [comment]
Scrapped Idea.
