### ISSUE TITLE
As a developer I want to error handle data

### ISSUE THREAD

**Issue by JoshHaase0** [Access-Point-Program/cohort-3-reports#5]
**GIVEN** There is no data to be shown
**WHEN** The user clicks on reports page
**OR** Display data is updated
**THEN** An error "nothing to see here, run some simulations and find the analysis here" is thrown
**AND** The error is displayed to the user
**AND** A button to redirect to the simulation page is displayed

### Acceptance Criteria 
- [x] A way to check if data is valid / exists
- [x] Able to catch the error and display it to the user
- [x] Passes unit tests

**Comment by Dpppatel** [comment]
Done
