### ISSUE TITLE
As a developer, we need to have Jasmine unit tests in our UI

### ISSUE THREAD

**Issue by chris-marfia** [Access-Point-Program/cohort-3-reports#52]
As a development team, we need to make sure that our Application has unit tests. All the components and features that require testing are documented below. 

### Checklist

- [x] TableComponent. Assignee: @Dpppatel 
- [x] MenuForm.  Assignee: (Elissa)
- [x] Sidebar.  Assignee: (@bioncoder)
- [x] Carousel.  Assignee: @MyeWhite 
- [x] Service1.  Assignee: (Elissa)

### Resources
- [Angular Testing Guide](https://angular.io/guide/testing)

### Acceptance Criteria
- Each feature and user interaction in the UI application has happy path testing completed 
- Each interaction with API calls has worst-case scenario testing

**Comment by epricewillis** [comment]
Integration testing for Menu-form, Service, Spring Application and Table

**Comment by epricewillis** [comment]
Tests if component appears, one for if it’s usable, one for if it responds back to it

**Comment by Dpppatel** [comment]
- all components are tested. 
      - AppComponent, 
      - TableComponent, 
      - MenuForm
      - Component, 
      - Charts, 
      - Pipe,
      - Carousel, 
      - Sidebar, 
      - Services,

**Comment by epricewillis** [comment]
Sidebar, Table, Browser, App, Service
Test the 9 spec files. End to end tests for each file

**Comment by MyeWhite** [comment]
Testing core functionality
